version: '3.8'

services:
  #  postgres:
  #    image: postgres:13
  #    container_name: postgres
  #    environment:
  #      POSTGRES_DB: jwt-day2
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: "010104"
  #    volumes:
  #      - postgres_data:/var/lib/postgresql/data
  #      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #    ports:
  #      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  pgsync-python:
    build: ./pgsync-python
    container_name: pgsync-python
    depends_on:
      #      - postgres
      - elasticsearch
    volumes:
      - ./pgsync-python:/app

volumes:
  #  postgres_data:
  esdata: